/* ==========================================================================
   DAFTAR HALAMAN / BAB — "Pelan-Pelan"
   --------------------------------------------------------------------------
   Digital Book:
   “Pelan-Pelan — Tentang kamu, tentang aku, dan tujuh tahun yang pernah kita punya.”
   Naskah asli & personal: 18 bab teks otentik + 1 bab album penutup (19 halaman).
   ========================================================================== */

export type ChapterVariant = 'cover' | 'text' | 'quote' | 'scrapbook' | 'minimal'

export interface Chapter {
  id: string
  slug: string
  title: string
  subtitle?: string
  variant: ChapterVariant
  bodyPlaceholder: string[]
}

export const chapters: Chapter[] = [
  {
    "id": "page-01",
    "slug": "bab-01-sebelum-membuka",
    "title": "Sebelum kamu membuka halaman ini",
    "subtitle": "Pelan2 aja.",
    "variant": "text",
    "bodyPlaceholder": [
      "Aku nggak tau harus mulai dari mana.",
      "Ada banyak hal yang selama ini sebenarnya pengen aku ceritain ke kamu, tapi selama kita masih bersama pun aku sering nggak tau gimana cara menyampaikannya. Kadang aku simpan sendiri, kadang aku pikir nanti aja, sampai akhirnya banyak hal yang nggak pernah bener2 keluar dari aku.",
      "Jadi kali ini aku coba tulis semuanya di sini.",
      "Bukan buat maksa kamu kembali.",
      "Bukan juga buat bikin kamu ngerasa bersalah atas keputusan yang kamu ambil.",
      "Aku cuma pengen kamu tau apa yang ada di kepalaku dan di hatiku selama ini. Tentang kita, tentang kesalahan yang baru sekarang bisa aku lihat lebih jelas, tentang hal2 yang kamu pernah ajarkan ke aku, dan tentang perasaan yang sampai sekarang masih ada.",
      "Aku nggak tau sejak kapan namamu jadi hal pertama yang pengen kutemui setiap hari.",
      "Hadirmu nggak pernah meminta untuk dicintai, tapi entah kenapa hatiku selalu memilihmu, bahkan pas logika mengajarkanku buat biasa aja.",
      "Kalo mencintaimu adalah sebuah perjalanan, maka aku nggak keberatan berjalan pelan2.",
      "Karna sama kamu, setiap langkah terasa seperti menemukan tempat yang selama ini kucari.",
      "Kamu nggak harus langsung baca semuanya.",
      "Buka kalo kamu memang lagi siap.",
      "Dan kalo nanti kamu berhenti di tengah jalan pun nggak apa2.",
      "Aku cuma berharap, kalo kamu membacanya, kamu bisa membacanya pelan2.",
      "Karna ini bukan sesuatu yang aku tulis dalam satu malam."
    ]
  },
  {
    "id": "page-02",
    "slug": "bab-02-dua-anak",
    "title": "Dulu, kita cuma dua anak yang nggak tau akan sejauh ini",
    "subtitle": "Awalnya sesederhana itu.",
    "variant": "text",
    "bodyPlaceholder": [
      "Dulu kita cuma kenal dari temen.",
      "Terus lanjut chattingan, saling cerita, saling curhat, sampai akhirnya kita sama2 mulai punya rasa.",
      "Aku bahkan nggak inget pasti siapa yang lebih dulu suka.",
      "Rasanya kita ngalamin itu bareng2.",
      "Yang paling aku inget justru waktu kita masih suka curi2 waktu buat ketemu. Kadang cuma buat ngobrol sebentar, bertukar kabar, atau sekadar bisa lihat satu sama lain.",
      "Waktu itu kita masih MTs.",
      "Kita pernah sembunyi2 buat ketemu, tuker surat, kasih barang2 kecil yang mungkin sekarang kelihatannya sederhana banget.",
      "Tapi waktu itu hal2 kecil itu cukup buat bikin kita senyum.",
      "Dan tanpa kita sadari, dari hal2 kecil itu kita tumbuh bareng.",
      "Kita nggak pernah tau waktu itu kalo dua anak yang cuma suka saling curhat ini akhirnya bakal berjalan sejauh tujuh tahun."
    ]
  },
  {
    "id": "page-03",
    "slug": "bab-03-mengingat-kita",
    "title": "Kalo aku mengingat kita",
    "subtitle": "Aku selalu ingat hal2 kecil.",
    "variant": "text",
    "bodyPlaceholder": [
      "Kalo aku mengingat kita, ternyata yang paling sering muncul bukan kejadian besar.",
      "Justru hal2 kecil.",
      "Aku inget masa kelas 12.",
      "Hampir tiap sore kita jalan2. Kadang beli makan, beli jajan, atau cuma muter2 nggak jelas tanpa tujuan.",
      "Nggak ada sesuatu yang istimewa sebenarnya.",
      "Tapi waktu itu aku bahagia banget.",
      "Sampai kadang aku pengen bisa ngestuck di waktu itu aja.",
      "Aku inget kita pernah menerobos hujan sore2 cuma buat jalan2.",
      "Bajuku sampai basah kuyup karna aku berusaha nutupin kamu dari hujan, dan malamnya aku malah demam.",
      "Kalo dipikir sekarang lucu juga.",
      "Tapi itu salah satu kenangan yang paling aku inget.",
      "Aku inget jalan2 malam menelusuri jalanan Kudus setelah les di GO.",
      "Aku inget Muria cuma karna kita pengen cari pentol.",
      "Aku inget perjalanan Jepara-Semarang.",
      "Mampir Indomaret cuma buat beli sesuatu.",
      "Jalan tanpa tujuan.",
      "VC malam.",
      "Berteduh waktu hujan.",
      "Jalan2 di mall.",
      "Photo booth.",
      "Lihat city lights.",
      "Foto2 random yang sampai sekarang masih ada di Google Photos.",
      "Dulu semua itu mungkin terasa biasa.",
      "Sekarang aku baru sadar, justru hal2 sederhana itu yang paling susah diganti.",

      "Aku selalu mengingatmu di hari2 yang kujalani.",
      "Bahkan jam, menit, dan detik pun rasanya nggak pernah luput dari bayanganmu.",
      "Rasanya bakal sulit banget kalo harus pura2 nggak inget apa2.",
      "Terlebih lagi karna aku masih ada tepat di kota ini—",
      "kota di mana cerita2 itu pernah kita tulis bareng.",
      "Jalanan yang selalu seolah berbisik di telingaku, tempat2 yang selalu memutar kenangan lama, dan semua hal baik yang selalu ngingetin aku sama kamu.",
      "Mungkin nanti akan ada waktu di mana suaraku udah nggak kamu kenali, wajahku udah nggak kamu ingat lagi, dan namaku udah nggak pernah kamu temui lagi.",
      "Tapi apa pun yang terjadi nanti, satu hal yang pasti: aku berjanji akan selalu mengingatmu."
    ]
  },
  {
    "id": "page-04",
    "slug": "bab-04-melihat-diri-sendiri",
    "title": "Setelah semuanya berhenti, aku mulai melihat diriku sendiri",
    "subtitle": "Untuk pertama kalinya aku bener2 berhenti dan melihat ke belakang.",
    "variant": "text",
    "bodyPlaceholder": [
      "Setelah semuanya berhenti, aku punya banyak waktu untuk mikir.",
      "Bukan cuma mikirin kenapa kita bisa sampai di titik ini.",
      "Tapi juga mikirin diriku sendiri.",
      "Aku mulai sadar kalo selama ini aku sering ngerasa udah ngelakuin yang terbaik.",
      "Dan mungkin memang aku berusaha.",
      "Tapi sekarang aku ngerti, **niat baik dan dampak yang dirasakan orang lain itu nggak selalu sama.**",
      "Aku bisa ngerasa lagi perhatian, tapi mungkin kamu tetap ngerasa sendirian.",
      "Aku bisa ngerasa lagi memahami kesibukanmu, tapi mungkin kamu tetap ngerasa jauh.",
      "Aku bisa ngerasa udah ngasih jawaban yang masuk akal, tapi ternyata itu bukan jawaban yang kamu butuhkan.",
      "Dan bagian itu yang paling banyak aku pikirkan.",
      "Aku nggak mau menyalahkan jarak.",
      "Aku nggak mau menyalahkan kesibukanmu.",
      "Aku juga nggak mau menyalahkan kamu.",
      "Aku cuma pengen jujur sama diriku sendiri tentang bagian mana dari diriku yang memang perlu diperbaiki."
    ]
  },
  {
    "id": "page-05",
    "slug": "bab-05-tentang-perasaanmu",
    "title": "Tentang perasaanmu yang dulu sering nggak aku mengerti",
    "subtitle": "Ini mungkin salah satu hal yang paling aku sesali.",
    "variant": "text",
    "bodyPlaceholder": [
      "Aku sekarang sadar, dulu aku sering terlalu cepat mencari jawaban sebelum bener2 memahami perasaanmu.",
      "Pas kamu bilang:",
      "**“Aku kok ngerasa jauh gitu sama kamu ya.”**",
      "Aku malah menjelaskan kalo kita sama2 punya kesibukan, kamu sedang PLT, dan kita memang sedang menjalani banyak hal.",
      "Padahal sekarang aku sadar...",
      "Mungkin waktu itu kamu nggak sedang meminta penjelasan.",
      "Kamu cuma sedang bilang:",
      "**“Aku ngerasa jauh.”**",
      "Dan mungkin jawaban yang kamu butuhkan waktu itu bukan penjelasan dari aku.",
      "Mungkin kamu cuma butuh aku bilang:",
      "**“Kamu ngerasa jauh yaa? Bagian mana yang paling kerasa buat kamu?”**",
      "Aku baru ngerti sekarang.",
      "Kadang seseorang nggak butuh kita langsung menyelesaikan perasaannya.",
      "Kadang dia cuma butuh didengar.",
      "Aku terlalu sering berpikir dari sisi logika, sementara kamu sedang berbicara dari sisi perasaan.",
      "Bukan karna aku nggak peduli.",
      "Aku cuma belum cukup ngerti cara mencintai seseorang dari sisi yang kamu butuhkan.",
      "Dan aku minta maaf untuk itu."
    ]
  },
  {
    "id": "page-06",
    "slug": "bab-06-yang-dulu-diajarkan",
    "title": "Hal2 yang dulu kamu ajarkan",
    "subtitle": "Banyak yang baru sekarang bener2 aku pahami.",
    "variant": "text",
    "bodyPlaceholder": [
      "Aku masih inget kamu pernah bilang:",
      "**“Ya gimana caranya kamu diruang aku sendiri itu, aku tetep bisa inget km.”**",
      "Dulu mungkin aku belum bener2 memahami kalimat itu.",
      "Sekarang aku mulai ngerti.",
      "Aku harus belajar bikin orang yang aku sayang ngerasa **diingat**, bukan cuma dicari.",
      "Kamu juga pernah ngajarin aku untuk mengolah kata2 dengan baik.",
      "Memahami dari hati.",
      "Mikirin sesuatu itu bukan cuma soal bener atau salah menurut logikaku, tapi juga gimana sesuatu itu diterima sama orang lain.",
      "Kamu pernah bilang aku jangan terlalu idealis.",
      "Aku harus keluar dari zona nyaman.",
      "Aku harus lebih perhatian.",
      "Kalo punya sesuatu, kalo bisa berbagi ya berbagi.",
      "Jangan terlalu mikirin diri sendiri.",
      "Dan mungkin dulu aku mendengar semuanya sebagai nasihat satu per satu.",
      "Sekarang aku melihat semuanya seperti satu kesatuan.",
      "Kamu sebenarnya lagi ngajarin aku gimana caranya jadi seseorang yang lebih peka terhadap orang yang aku sayang.",
      "Dan ternyata banyak dari hal itu memang masih harus aku pelajari."
    ]
  },
  {
    "id": "page-07",
    "slug": "bab-07-belajar-dari-banyak-hal",
    "title": "Aku belajar dari banyak hal",
    "subtitle": "Bukan untuk mencari siapa yang salah.",
    "variant": "text",
    "bodyPlaceholder": [
      "Selama sekitar sebulan ini aku bener2 banyak belajar.",
      "Aku baca banyak hal.",
      "Aku dengerin berbagai sudut pandang.",
      "Aku coba memahami lagi tentang komunikasi, tentang hubungan, tentang gimana seseorang menerima perhatian, tentang emosi, dan tentang kesalahan2 yang mungkin selama ini nggak aku sadari.",
      "Bukan buat mencari pembenaran.",
      "Bukan buat menentukan siapa yang paling salah.",
      "Tapi karna aku pengen ngerti.",
      "Aku mulai belajar satu pola yang sekarang terus aku coba ingat:",
      "**Dengar → Validasi → Gali → Baru cari solusi.**",
      "Bukan:",
      "**Dengar → Analisis → Jelaskan → Selesaikan.**",
      "Aku belajar untuk bertanya sebelum berasumsi.",
      "Belajar untuk memahami sebelum menjelaskan.",
      "Belajar untuk menerima kalo sudut pandangku nggak selalu menjadi satu2nya yang benar.",
      "Dan yang paling penting, aku belajar kalo pas seseorang yang aku sayang lagi ngerasa berat, aku nggak harus selalu punya jawaban.",
      "Kadang aku cuma perlu ada."
    ]
  },
  {
    "id": "page-08",
    "slug": "bab-08-belum-berubah",
    "title": "Aku nggak mau bilang aku udah berubah",
    "subtitle": "Aku nggak mau menjanjikan sesuatu yang belum bisa aku buktikan.",
    "variant": "text",
    "bodyPlaceholder": [
      "Aku nggak mau bilang:",
      "**“Aku udah berubah.”**",
      "Karna aku rasa kalimat itu terlalu mudah diucapkan.",
      "Aku juga nggak mau bilang aku bakal jadi sempurna.",
      "Aku masih manusia.",
      "Aku masih bisa salah.",
      "Tapi sekarang setidaknya aku udah lebih ngerti bagian mana dari diriku yang harus aku perbaiki.",
      "Aku sedang belajar lebih peka.",
      "Belajar lebih bisa mendengarkan.",
      "Belajar nggak buru2 memberikan solusi.",
      "Belajar membedakan kapan seseorang cuma ingin didengar dan kapan dia memang meminta pendapat.",
      "Belajar nggak terlalu idealis sama pikiranku sendiri.",
      "Belajar lebih berani menunjukkan perasaan.",
      "Belajar jadi seseorang yang bisa bikin orang yang aku sayang ngerasa aman dan nyaman.",
      "Aku nggak tau nanti perubahan ini akan membawa aku ke mana.",
      "Tapi aku tau aku nggak mau berhenti di penyesalan.",
      "Aku pengen semua yang terjadi ini bener2 bikin aku jadi orang yang lebih baik.",
      "Bukan cuma untuk kamu.",
      "Tapi juga untuk diriku sendiri dan orang2 yang akan ada dalam hidupku nanti.",
      "Dan kalo boleh berharap, aku tetap pengen bareng kamu pas aku udah jadi lebih baik nanti."
    ]
  },
  {
    "id": "page-09",
    "slug": "bab-09-maaf",
    "title": "Maaf",
    "subtitle": "Satu per satu.",
    "variant": "text",
    "bodyPlaceholder": [
      "Aku minta maaf.",
      "Karna ada saatnya aku nggak cukup mendengar kamu.",
      "Karna aku terlalu cepat mikirin maksudku sendiri.",
      "Karna ada saatnya kamu mungkin cuma ingin dipahami, tapi aku malah memberikan penjelasan.",
      "Karna aku kurang sering mulai VC dan bikin komunikasi kita lebih banyak kamu yang mulai.",
      "Karna aku kurang bisa memahami masalah emosionalmu.",
      "Karna aku kurang bisa bikin kamu ngerasa nyaman pas kita lagi LDR.",
      "Karna aku terlalu takut ngeganggu pas kamu sibuk, sampai akhirnya mungkin justru bikin jarak di antara kita makin kerasa.",
      "Aku minta maaf untuk semua kekuranganku selama tujuh tahun.",
      "Untuk kesalahan yang aku sadari.",
      "Dan untuk kesalahan yang mungkin baru akan aku pahami setelah ini.",
      "Aku juga minta maaf untuk semua hal yang pernah bikin kamu capek, kecewa, ngerasa sendiri, atau ngerasa nggak cukup dimengerti.",
      "Aku nggak bisa mengulang waktu.",
      "Tapi aku nggak mau semua ini berhenti cuma sebagai penyesalan."
    ]
  },
  {
    "id": "page-10",
    "slug": "bab-10-tujuh-tahun-disyukuri",
    "title": "Tujuh tahun yang aku syukuri",
    "subtitle": "Kalo ditanya apakah aku menyesal pernah memilih kamu, jawabannya nggak.",
    "variant": "text",
    "bodyPlaceholder": [
      "Tujuh tahun itu bukan waktu yang sebentar buat aku.",
      "Kita tumbuh bareng.",
      "Dari dua anak yang awalnya cuma saling curhat, sampai akhirnya menjalani banyak fase kehidupan bersama.",
      "Aku pernah bahagia banget sama kamu.",
      "Aku pernah ngerasa punya partner yang selalu ada dan ngedukung aku.",
      "Aku pernah ngerasa punya seseorang yang bisa aku ceritain banyak hal.",
      "Dan aku bersyukur pernah ngerasain semua itu.",
      "Aku nggak mau menganggap tujuh tahun kita gagal hanya karna akhirnya kita sampai di titik ini.",
      "Ada bagian yang menyakitkan.",
      "Ada kesalahan.",
      "Ada hal2 yang seharusnya bisa aku lakukan lebih baik.",
      "Tapi ada juga begitu banyak hal baik yang akan selalu aku syukuri.",
      "Kalo waktu bisa diulang dan aku kembali menjadi diriku yang dulu...",
      "Aku rasa aku tetap akan memilih kamu.",
      "Bukan karna aku menganggap semuanya harus berakhir berbeda.",
      "Tapi karna kalo aku dikasih kesempatan buat mengenal kamu sekali lagi, aku tetap mau.",
      "Mungkin kali ini aku bisa lebih banyak mendengar.",
      "Mungkin aku bisa lebih ngerti kamu.",
      "Mungkin aku bisa jadi pria yang lebih baik dari aku yang dulu.",
      "Tapi setidaknya aku tau, aku nggak pernah menyesal pernah memilih kamu."
    ]
  },
  {
    "id": "page-11",
    "slug": "bab-11-hal-kecil-yang-tinggal",
    "title": "Hal2 kecil tentang kamu yang masih tinggal",
    "subtitle": "Kadang yang paling susah hilang justru yang paling sederhana.",
    "variant": "scrapbook",
    "bodyPlaceholder": [
      "Ada banyak hal tentang kamu yang masih tinggal.",
      "Nomi.",
      "Nopi.",
      "Lego bunga2.",
      "Bunga yang pernah aku kasih.",
      "Surat2 kecil.",
      "Hadiah2 yang pernah kita tukarkan.",
      "Foto random.",
      "Foto perjalanan.",
      "Panggilan **“noney”**.",
      "Hal2 kecil yang mungkin buat orang lain nggak berarti apa2.",
      "Tapi buat aku punya cerita sendiri.",
      "Kadang aku membuka Google Photos dan menemukan foto yang bahkan mungkin udah lama nggak aku lihat.",
      "Terus tiba2 aku inget lagi tempatnya.",
      "Hari itu.",
      "Obrolannya.",
      "Atau cuma perasaan waktu itu.",
      "Aku nggak mau nyimpen semua itu buat bikin diriku terus hidup di masa lalu.",
      "Aku cuma nggak mau pura2 bahwa semua itu nggak pernah berarti.",
      "Karna memang berarti."
    ]
  },
  {
    "id": "page-12",
    "slug": "bab-12-tentang-kamu",
    "title": "Tentang kamu",
    "subtitle": "Kenapa selama itu aku memilih kamu.",
    "variant": "text",
    "bodyPlaceholder": [
      "Aku suka sifat lucumu.",
      "Aku suka sifat manjamu.",
      "Aku suka pas kamu butuh aku.",
      "Aku suka cara kamu sayang sama aku pas aku sehat maupun pas aku sakit.",
      "Aku suka perhatian2 kecilmu.",
      "Memanggilku “noney”.",
      "Ngingetin aku pas aku salah.",
      "Memberikan saran tentang kehidupanku.",
      "Bahkan kadang hal yang dulu mungkin terasa biasa, sekarang baru terasa berharga.",
      "Kamu juga orang yang lembut.",
      "Aku tau kamu nggak cocok dibentak.",
      "Nggak cocok diajak bicara dengan nada tinggi.",
      "Dan seharusnya aku lebih memahami itu.",
      "Tapi lebih dari semua sifat itu, aku nyaman sama kamu karna dulu kamu bisa bikin aku ngerasa aman pas cerita.",
      "Aku bisa cerita apa aja.",
      "Entah akhirnya kita ketawa, serius, atau cuma ngobrol nggak jelas.",
      "Rasanya nyaman.",
      "Kamu bukan cuma pasangan buat aku.",
      "Kamu partner seperjalanan.",
      "Seseorang yang bikin hidupku kerasa lebih menyenangkan dan lebih berarti.",
      "“Kalo cinta mempunyai nama, menurutmu akan bernama siapa?”",
      "Aku mungkin akan terdiam sebentar, lalu nyebut namamu pelan2, seolah takut suara itu bikin kamu tau betapa dalamnya perasaanku.",
      "Karna seandainya cinta bener2 punya nama, aku pengen dia punya namamu. Bukan karna kamu manusia yang sempurna, tapi karna sama kamu aku nemuin sesuatu yang nggak pernah aku temuin di nama2 lain.",
      "Cinta, buat aku, bukan sekadar debar pas lihat kamu. Dia adalah rasa pengen tetap tinggal pas hari2 nggak lagi mudah. Keinginan buat ngerti pas kata2 nggak mampu ngejelasin, dan keberanian buat tetap memilih seseorang setelah tau segala kurangnya.",
      "Mungkin nanti waktu bakal ngubah banyak hal. Wajah bakal menua, jarak mungkin memisahkan, dan kehidupan bakal ngebawa kita ke musim2 yang nggak pernah kita rencanakan.",
      "Tapi kalo suatu hari seseorang nanya ke aku,",
      "**“Pernahkah kamu bener2 mencintai seseorang?”**",
      "Aku pengen senyum dan ngejawab,",
      "**“Pernah.”**",
      "Dan kalo cinta mempunyai nama,",
      "barangkali aku pernah nyebut satu nama dengan begitu tulus",
      "sampai namanya tinggal jauh lebih lama daripada cinta itu sendiri.",
      "Dan mungkin itu juga alasan kenapa kehilangan kamu terasa sebesar ini."
    ]
  },
  {
    "id": "page-13",
    "slug": "bab-13-kalo-suatu-hari",
    "title": "Kalo suatu hari...",
    "subtitle": "Ini bukan permintaan. Cuma sebuah harapan.",
    "variant": "text",
    "bodyPlaceholder": [
      "Kalo suatu hari nanti kita dipertemukan lagi...",
      "Aku nggak tau kita akan menjadi apa.",
      "Aku juga nggak tau apakah kamu masih akan melihat aku dengan cara yang sama.",
      "Kalo suatu hari kamu kasih aku kesempatan lagi, aku nggak pengen cuma balik ke hubungan kita yang dulu.",
      "Aku pengen kita mulai lagi sebagai dua orang yang udah sama2 belajar.",
      "Mungkin membaca buku yang sama untuk kedua kalinya nggak akan merubah endingnya.",
      "Tapi kalo dua penulisnya udah bertumbuh dan saling mengerti, mereka akan selalu bisa membuat bab baru.",
      "Aku pengen lebih ngerti kamu.",
      "Lebih dengerin kamu.",
      "Lebih peka sama hal2 kecil.",
      "Lebih berani nunjukin kalo aku sayang, bukan cuma menganggap kamu pasti tau.",
      "Aku pengen kamu ngerasa nyaman cerita ke aku lagi.",
      "Dan kalo kamu lagi capek sama dunia, setidaknya kamu tau ada aku yang mau dengerin kamu tanpa buru2 ngejelasin atau nyari solusi.",
      "Biar orang lain berlomba mengagumi hebat dan cantiknya kamu. Di depanku, kamu nggak perlu pura2 selalu utuh.",
      "Karna rasa sayang yang aku punya bukan cuma tentang menyukai sempurnamu, tapi tentang menerima setiap retak yang kamu sembunyikan dari dunia.",
      "Orang2 mungkin gampang singgah pas kamu lagi bersinar dan bahagia, lalu menjauh pas kelopaknya memudar dan harimu lagi redup.",
      "Tapi aku nggak pernah mau menyayangimu dengan cara sesempit itu.",
      "Kalo merayakan bahagiamu adalah hal yang mudah buat siapa aja, maka menemani lukamu adalah hal yang paling pengen kulakukan dengan tulus.",
      "Karna dari dulu, aku nggak pernah mencari kesempurnaan dari kamu.",
      "Taruh aja di sini gelisah yang selalu kamu simpan sendiri di balik dinding kamar, atau rasa lelah yang nggak pernah berani kamu tunjukin ke siapa pun.",
      "Aku pengen jadi tempat paling teduh buat segala kurangmu, tempat di mana kamu bisa berhenti pura2 kuat tanpa rasa takut.",
      "Maka kalo suatu hari kamu ngerasa capek sama dunia, ruang ini selalu terbuka buat kamu.",
      "Jangan rapikan tangismu, jangan sembunyikan lelahmu.",
      "Karna pas orang lain mungkin cuma bertepuk tangan buat hebatmu, di sini ada aku yang selalu siap menemani rapuhmu—sampai kamu sadar bahwa kamu tetaplah seseorang yang utuh dan berharga buat aku.",
      "Tapi yaa... itu semua cuma kalo suatu hari kamu sendiri yang mau.",
      "Aku nggak mau memaksa kamu buat kasih kesempatan itu."
    ]
  },
  {
    "id": "page-14",
    "slug": "bab-14-jalan-berbeda",
    "title": "Tapi kalo ternyata jalan kita memang berbeda",
    "subtitle": "Karna pilihan itu tetap milikmu.",
    "variant": "text",
    "bodyPlaceholder": [
      "Aku nggak tau apakah suatu hari nanti kita akan kembali atau nggak.",
      "Aku juga nggak mau pura2 seolah aku udah nggak berharap.",
      "Karna kenyataannya, aku masih berharap.",
      "Aku masih pengen kamu.",
      "Bukan cuma sebagai seseorang yang pernah aku cintai selama tujuh tahun, tapi sebagai seseorang yang sampai sekarang masih pengen aku temui lagi, aku ajak cerita lagi, aku ajak ketawa lagi, dan kalo Tuhan masih kasih jalan... aku masih pengen jalan bareng kamu lagi.",
      "Aku nggak mau bohong dengan bilang aku udah sepenuhnya ikhlas atau udah nggak berharap apa2.",
      "Karna kenyataannya nggak begitu.",
      "Aku masih berharap.",
      "Aku masih membayangkan kemungkinan kalo suatu hari nanti kita bisa ketemu lagi sebagai dua orang yang udah sama2 belajar dari semua yang pernah terjadi.",
      "Aku masih pengen punya kesempatan buat mengenal kamu lagi. Bukan cuma sebagai orang yang pernah menjadi pacarku, tapi sebagai seseorang yang mungkin suatu hari bisa aku cintai dengan cara yang lebih baik dari sebelumnya.",
      "Aku masih pengen nemenin kamu.",
      "Masih pengen denger cerita2 kecil kamu.",
      "Masih pengen tau kamu hari ini capek atau nggak, lagi seneng atau nggak, lagi butuh ditemenin atau cuma butuh didengerin.",
      "Masih pengen ngerasain hal2 sederhana yang dulu mungkin aku anggap biasa.",
      "Dan kalo kamu tanya apakah setelah semua yang terjadi aku masih mau memilih kamu?",
      "Jawabannya masih sama.",
      "Aku masih mau kamu.",
      "Aku masih memilih kamu.",
      "*I want to be chosen again, just as I kept choosing you, over and over again.*",
      "Mungkin memang nggak pernah kerasa aneh pas kita terus memilih orang yang kita sayang. Yang berat itu pas kita masih terus memilih dia, sementara kita nggak tau apakah suatu hari nanti dia masih akan memilih kita lagi.",
      "Bukan karna aku nggak bisa hidup tanpa kamu. Aku bisa.",
      "Tapi karna setelah semua yang aku pikirkan selama ini, aku sadar bahwa kalo suatu hari aku diberi kesempatan untuk memilih lagi, aku tetap ingin mengenal kamu, tetap ingin mencintai kamu, dan tetap ingin mencoba membangun sesuatu sama kamu.",
      "Dan mungkin di luar sana memang ada orang yang lebih pintar bikin kamu ketawa, atau lebih gampang nemuin kata2 yang dulu nggak pernah bisa aku temuin.",
      "Aku sempat takut cinta itu cuma soal siapa yang lebih layak buat tinggal.",
      "Tapi akhirnya aku mikir... aku sayang sama kamu bukan buat balapan atau mengalahkan siapa2.",
      "Aku belajar buat nggak menjadikan rasa takut kehilangan sebagai alasan untuk membatasi ruangmu.",
      "Karna mungkin rasa sayang itu sesederhana ini:",
      "**tau kamu bisa memilih siapa aja, tapi di dalam hati kecilku, aku tetap berharap namaku masih ada di antara pilihan itu.**",
      "Aku nggak tau apakah kesempatan itu akan datang.",
      "Aku nggak tau apakah kamu masih punya sedikit ruang untuk aku di hidupmu.",
      "Aku juga nggak tau apakah suatu hari nanti perasaan kamu akan berubah.",
      "Dan aku nggak mau memaksa semuanya harus terjadi.",
      "Ada satu kalimat yang sampai sekarang sebenarnya masih pengen banget aku denger:",
      "**“aku mau kasih kamu satu kesempatan lagi.”**",
      "Aku tau, kalo kesempatan itu bener2 datang, semuanya nggak akan langsung kembali seperti dulu. Mungkin masih banyak hal yang harus kita pelajari, dan rasa takut buat ngulang kesalahan yang sama mungkin masih ada.",
      "Tapi seandainya ruang itu ada, aku pengen ngejalaninnya dengan cara yang berbeda. Bukan cuma demi bisa bareng kamu lagi, tapi karna aku pengen jadi seseorang yang bener2 pantas buat kamu pilih lagi.",
      "Aku cuma pengen kamu tau satu hal yang mungkin selama ini belum pernah bener2 bisa aku sampaikan dengan baik:",
      "**aku masih sangat menginginkan kamu.**",
      "Kalo suatu hari kamu kembali membuka sedikit ruang itu, aku masih ada.",
      "Dan kalo suatu hari kamu memilih untuk kembali, aku nggak perlu merasa menang.",
      "Aku cuma pengen jadi tempat yang tenang dan nyaman, yang kamu ingat pas harimu mulai terasa sepi.",
      "Aku nggak bisa menjanjikan semuanya akan sempurna.",
      "Tapi aku bisa bilang dengan jujur bahwa kalo suatu hari kamu memberi aku kesempatan lagi, aku nggak akan menganggap kesempatan itu sebagai sesuatu yang biasa.",
      "Karna setelah kehilangan kamu, aku jadi tau betapa berharganya kesempatan untuk bisa mencintai kamu."
    ]
  },
  {
    "id": "page-15",
    "slug": "bab-15-terima-kasih",
    "title": "Terima kasih",
    "subtitle": "Untuk tujuh tahun yang pernah kita punya.",
    "variant": "text",
    "bodyPlaceholder": [
      "Terima kasih udah milih aku buat nemenin kamu selama tujuh tahun terakhir ini.",
      "Tujuh tahun yang kalo dipikir2 ternyata panjang banget.",
      "Aku banyak belajar dari kamu.",
      "Banyak ngerasain seneng, bahagia, jatuh cinta, ketawa bareng, sedih bareng, sampai ngerasain gimana rasanya punya seseorang yang bener2 aku sayang.",
      "Selama tujuh tahun itu, hatiku juga pernah penuh banget sama kasih sayangmu.",
      "Dan jujur, aku bersyukur pernah ngerasain semuanya sama kamu.",
      "Aku juga mau minta maaf.",
      "Maafin aku kalo selama tujuh tahun ini kamu malah lebih sering nangis karna aku. Kalo pernah ada hal yang aku lakuin, entah sengaja atau nggak sengaja, yang akhirnya bikin kamu sakit hati.",
      "Maafin aku kalo ada perkataan atau sikapku yang waktu itu menurutku biasa aja, tapi ternyata buat kamu nggak sesederhana itu.",
      "Mungkin ada banyak hal yang waktu itu nggak aku sadari. Dan mungkin ada juga yang baru sekarang aku ngerti setelah semuanya berhenti.",
      "Jujur, dari dalam hatiku yang paling dalam, aku sebenarnya masih pengen selalu bareng kamu.",
      "Aku pengen ngejalanin susah seneng berdua. Pengen nemenin kamu di banyak fase hidupmu. Pengen lihat kamu tumbuh, aku juga tumbuh, sampai kalo memang Tuhan kasih kesempatan, kita bisa sama2 tua nanti.",
      "Dan kalo suatu hari itu bener2 terjadi, aku pasti pengen terus berusaha jadi lebih baik buat kamu dan buat hubungan kita.",
      "Aku pengen mencintai kamu dan menyayangi kamu sampai waktu sendiri bosan berputar.",
      "Sampai bintang2 di atas sana memutuskan buat padam karna iri melihat binar cahaya di matamu yang menurutku jauh lebih terang.",
      "Mungkin kedengarannya lebay.",
      "Tapi yaa... lihat aja betapa seriusnya aku dalam mencintai kamu, sayang.",
      "Aku pengen mencintai kamu sampai semesta lupa caranya bekerja. Sampai seluruh gravitasi di dunia ini menyerah dan membiarkan kita melayang berdua tanpa arah.",
      "Buat aku, kayaknya nggak ada kamus yang cukup tebal buat menjelaskan sempurnanya kamu di mataku.",
      "Dan nggak ada keabadian yang cukup panjang buat membuktikan betapa keras kepalanya aku dalam mencintai kamu.",
      "Aku tau aku bukan pria yang sempurna.",
      "Bahkan setelah semua yang terjadi, aku masih punya banyak hal yang harus aku perbaiki dari diriku sendiri.",
      "Tapi kalo ada satu hal yang dari dulu nggak pernah aku ragukan, itu adalah betapa sayangnya aku sama kamu.",
      "Dan selama aku masih dikasih kesempatan buat mencintai kamu, aku akan selalu berusaha memberikan yang terbaik yang aku punya.",
      "Bukan karna aku mau bikin kamu ngerasa harus kembali.",
      "Aku cuma pengen kamu tau, sebesar itu rasa sayangku ke kamu selama ini.",
      "But in sastra we say...",
      "Aku pernah mengira seseorang datang cuma buat mengisi sebentar ruang yang kosong.",
      "Tapi sejak kenal kamu, ternyata aku salah.",
      "Ada seseorang yang datang pelan2, awalnya cuma jadi tempat cerita, tempat curhat, tempat ketawa, sampai akhirnya tanpa sadar jadi orang yang paling pengen aku punya di hidupku.",
      "Aku suka banyak hal kecil tentang kamu.",
      "Cara kamu cerita.",
      "Cara kamu ketawa.",
      "Cara kamu kadang manja.",
      "Cara kamu perhatian sama hal2 kecil.",
      "Dan entah kenapa, kehadiran kamu dulu bisa bikin hari yang biasa aja terasa lebih menyenangkan.",
      "Aku nggak tau nanti hidup bakal membawa kita ke mana.",
      "Mungkin memang akan ada jarak.",
      "Mungkin waktu bakal bikin banyak hal berubah.",
      "Mungkin nanti kita bener2 cuma jadi bagian dari masa lalu masing2.",
      "Tapi untuk sekarang, aku cuma tau satu hal.",
      "Aku pernah menemukan kamu.",
      "Dan dari sekian banyak orang yang pernah hadir di hidupku, kamu jadi salah satu nama yang paling susah buat aku anggap cuma sebagai kenangan.",
      "Mungkin alasan aku masih mengingat kamu sampai sekarang bukan karna kenangan tentang kamu terlalu kuat.",
      "Mungkin karna waktu sama kamu, aku pernah jadi seseorang yang bener2 bahagia.",
      "Seseorang yang ngerasa hidupnya penuh cuma karna ada kamu di dalamnya.",
      "Dan mungkin itu juga alasan kenapa sampai sekarang aku masih susah menganggap semuanya cuma sebagai masa lalu.",
      "Karna gimana caranya sesuatu yang pernah bikin aku sebahagia itu tiba2 harus aku anggap sebagai sesuatu yang nggak pernah ada?"
    ]
  },
  {
    "id": "page-16",
    "slug": "bab-16-mengingat-aku",
    "title": "Kalo suatu hari kamu mengingat aku",
    "subtitle": "Semoga bukan cuma akhirnya yang kamu ingat.",
    "variant": "text",
    "bodyPlaceholder": [
      "Kalo suatu hari nanti kamu mengingat aku...",
      "Aku nggak pengen kamu cuma inget gimana semuanya berakhir.",
      "Kalo bisa, ingat juga dua anak yang dulu saling curhat dan nggak tau akan berjalan sejauh ini.",
      "Ingat surat2 kecil.",
      "Ingat sore2 kelas 12.",
      "Ingat kita yang cuma keluar buat beli jajan.",
      "Ingat jalanan Kudus setelah les GO.",
      "Ingat Muria dan pentol.",
      "Ingat hujan yang bikin bajuku basah sampai demam.",
      "Inget pas kamu tetap pengen jenguk aku dari Kudus waktu aku dirawat di Demak.",
      "Ingat semua hal kecil yang pernah bikin kita ketawa.",
      "Nggak perlu ngerasa bersalah.",
      "Nggak perlu ngerasa terbebani.",
      "Aku cuma berharap kalo suatu hari kamu mengingatku, yang muncul bukan cuma rasa sakit.",
      "Semoga ada sedikit senyum juga.",
      "Karna pas aku inget kamu, meskipun sekarang ada rasa sakitnya, aku tetap masih bisa nemuin banyak hal yang bikin aku senyum.",

      "Kalo suatu hari kita bener2 tiba di ujung jalan yang berbeda, jangan buru2 menghapusku dari hidupmu.",
      "Biarkan aku tinggal sebagai sesuatu yang nggak lagi kamu genggam, tapi sesekali masih bisa kamu temukan.",
      "Ingatlah aku pas langit lagi baik2 saja. Pas angin memilih berjalan pelan, atau pas hujan datang tanpa suara.",
      "Bukan karna kamu masih sayang sama aku, tapi karna pernah ada seseorang yang dengan sepenuh hati berusaha menyayangimu.",
      "Kalo suatu hari ada lagu yang terdengar terlalu akrab, jangan buru2 diganti. Dengarkan sampai selesai. Barangkali ada sebagian kecil dariku yang tertinggal di antara bait2nya, menunggu kamu mengenangnya sekali lagi.",
      "Dan bila suatu sore kamu melihat pemandangan yang pernah sering kubicarakan, tersenyumlah sebentar. Nggak perlu mencari keberadaanku.",
      "Cukup ingat kalo pernah ada seseorang yang mengaitkan seluruh keindahan dunia dengan caramu hadir.",
      "Aku cuma pengen, seandainya namaku suatu hari menghilang dari percakapanmu, semoga kenangan kita nggak ikut kehilangan tempatnya.",
      "Kalo pada akhirnya kamu berhasil melupakanku, semoga dunia selalu memperlakukanmu dengan lembut.",
      "Tapi kalo masih ada satu sudut kecil dalam ingatanmu yang menolak menutup pintunya, biarkan aku tetap tinggal di sana bukan sebagai penyesalan, melainkan sebagai seseorang yang pernah begitu tulus berharap kita nggak perlu belajar menjadi asing.",
      "Di bumi yang luas ini, ketemu sama kamu adalah hal yang paling aku syukuri sepanjang hidup.",
      "Di perjalananmu yang jauh itu, luaskan pandanganmu, tabahkan hatimu. Aku tau kamu kuat menghadapi dunia dan segala badainya.",
      "Biar rentang doaku yang memelukmu, menjagamu di setiap jalan yang kamu tempuh.",
      "Dan semoga kelak kamu tau, bahwa rasa sayangku nggak pernah surut, meskipun akhirnya jalan kita sekarang berbeda."
    ]
  },
  {
    "id": "page-17",
    "slug": "bab-17-dari-aku-yang-sekarang",
    "title": "Untuk kamu, dari aku yang sekarang",
    "subtitle": "Ada banyak hal yang dulu nggak sempat aku katakan.",
    "variant": "text",
    "bodyPlaceholder": [
      "Aku nggak tau kamu akan melihat aku seperti apa setelah membaca ini.",
      "Aku juga nggak tau apakah tulisan ini akan mengubah sesuatu atau nggak.",
      "Dan aku nggak mau menjadikan tulisan ini sebagai alat untuk mengubah keputusanmu.",
      "Aku cuma ingin kamu tau bahwa aku bener2 belajar dari semuanya.",
      "Dari kesalahan yang aku lakukan.",
      "Dari hal2 yang pernah kamu keluhkan.",
      "Dari nasihat yang pernah kamu kasih.",
      "Dari semua hal yang dulu mungkin aku dengar, tapi belum bener2 aku pahami.",
      "Sekarang aku sedang berusaha membawa semuanya ke dalam hidupku.",
      "Aku ingin menjadi orang yang lebih peka.",
      "Lebih bisa mendengar.",
      "Lebih bisa memahami.",
      "Lebih bisa menyesuaikan diri dengan orang yang aku sayang.",
      "Dan kalo suatu hari aku kembali mencintai seseorang, aku ingin mencintai dia dengan cara yang lebih sehat dari dulu.",
      "Tapi kalo suatu hari orang itu ternyata masih kamu...",
      "Aku akan sangat bersyukur.",
      "Karna jujur, sampai sekarang aku masih sayang.",
      "Masih mencintai kamu.",
      "Dan masih menyayangi kamu sepenuh hati.",

      "Aku mencintaimu dengan caraku, seperti hujan yang turun menemui tanah tanpa perlu diminta.",
      "Aku tau dulu aku punya banyak salah, tapi izinkan aku tetap menyayangimu dengan caraku sendiri.",
      "Aku nggak meminta balasan atas rasa ini.",
      "Dan saat waktu mengajarkanku tentang keikhlasan, aku perlahan belajar melepaskanmu, tanpa harus melupakanmu.",
      "Bukan untuk menahanmu, cuma untuk mengingat bahwa pernah ada seseorang yang kucintai dengan sepenuh jiwa."
    ]
  },
  {
    "id": "page-18",
    "slug": "bab-18-halaman-terakhir",
    "title": "Halaman terakhir",
    "subtitle": "Pelan2 sampai sini.",
    "variant": "text",
    "bodyPlaceholder": [
      "Akhirnya sampai juga di halaman terakhir.",
      "Jujur aku nggak tau setelah kamu baca semuanya nanti kamu bakal ngerasa apa.",
      "Mungkin biasa aja.",
      "Mungkin sedih.",
      "Mungkin kesel.",
      "Mungkin bingung.",
      "Atau mungkin nggak ngerasa apa2.",
      "Dan semuanya nggak apa2.",
      "Kamu nggak punya kewajiban buat membalas semua ini.",
      "Nggak harus kasih jawaban.",
      "Nggak harus kasih kepastian.",
      "Aku cuma pengen, untuk sekali ini, kamu tau apa yang sebenarnya selama ini ada di kepalaku dan di hatiku.",
      "Aku masih sayang kamu.",
      "Masih.",
      "Dan mungkin untuk waktu yang nggak sebentar, rasa itu masih akan ada.",
      "Tapi aku juga mulai ngerti kalo sayang sama seseorang nggak berarti aku berhak meminta dia tetap tinggal.",
      "Aku masih berharap.",
      "Aku nggak mau bohong soal itu.",
      "Tapi keputusan tetap ada di kamu.",
      "Aku cuma bisa belajar dari semua yang udah terjadi.",
      "Tentang gimana harus lebih banyak dengerin.",
      "Tentang memahami sebelum menjelaskan.",
      "Tentang perhatian yang nggak cuma ada pas diminta.",
      "Tentang gimana bikin orang yang kita sayang ngerasa aman buat cerita.",
      "Dan tentang gimana mencintai seseorang dengan cara yang nggak bikin dia ngerasa sendirian.",
      "Kalo suatu hari jalan kita ketemu lagi, aku berharap saat itu aku udah jadi orang yang lebih siap.",
      "Bukan cuma lebih siap buat mencintai kamu, tapi juga lebih siap buat menjaga hubungan itu kalo memang kamu masih mau.",
      "Tapi kalo ternyata jalan kita memang berhenti sampai di sini...",
      "yaudah.",
      "Mungkin itu memang bagian yang harus aku terima.",
      "Aku tetap akan bersyukur pernah punya kamu.",
      "Pernah nemenin kamu.",
      "Pernah ditemenin kamu.",
      "Pernah ketawa bareng kamu.",
      "Pernah cerita banyak hal sama kamu.",
      "Dan pernah dicintai sama kamu selama tujuh tahun.",
      "Terima kasih udah milih aku buat nemenin kamu selama itu.",
      "Maaf untuk semua hal yang pernah bikin kamu sakit.",
      "Dan terima kasih untuk semua hal yang pernah bikin aku bahagia.",
      "Aku nggak tau nanti kita akan jadi apa.",
      "Tapi aku tau satu hal.",
      "Aku akan selalu menganggap tujuh tahun itu sebagai salah satu bagian paling berarti dalam hidupku.",
      "Jaga diri baik2 yaa.",
      "— honey bunny sweetymu"
    ]
  },
  {
    "id": "page-19",
    "slug": "bab-19-album-kenangan",
    "title": "Album Kenangan",
    "subtitle": "Tujuh tahun dalam bingkai2 kecil.",
    "variant": "scrapbook",
    "bodyPlaceholder": [
      "Ada hal2 yang nggak bisa dijelaskan dengan kata2, tapi tersimpan rapi di setiap sudut foto ini.",
      "Dari masa awal di MTs, hari2 di MAN, sudut2 kota, sampai perjalanan yang pernah kita lewati bareng.",
      "Setiap foto di bawah punya ceritanya sendiri. Terima kasih untuk tujuh tahun yang pernah ada."
    ]
  }
]

/** Jumlah halaman total. Dipakai footer & indikator navigasi. */
export const totalChapters = chapters.length

/** Cari bab berdasarkan `id` (mis. 'page-07'). */
export function getChapterById(id: string): Chapter | undefined {
  return chapters.find((chapter) => chapter.id === id)
}
